### ISSUE TITLE
Custom css is not applied by example config.toml

### ISSUE THREAD

**Issue by jlandowner** [dataCobra/hugo-vitae#17]
I found an incorrect example in config.toml.
I set custom css option as referenced in example `exampleSite/config.toml`, but it was not be applied.

```toml:exampleSite/config.toml
[params]
	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"
```
css is here.
```zsh
$ ls -lR ./static 
static/css:
total 8
-rw-r--r--  1 jlandowner  staff  203  5 19 21:06 custom.css <- not applied
```

I found the generated link tag `href` is incorrect.
```html
<link rel="stylesheet" type="text/css" media="screen" href="http://localhost:1313/css/css/custom.css">
```

This is because `layouts/partials/head.html` already specifies "css" in fixed path.

```html:layouts/partials/head.html
<!-- Use customcss if you like -->
  {{- if isset .Site.Params "customcss" -}}
  <link rel="stylesheet" type="text/css" media="screen" href="{{ .Site.BaseURL }}css/{{ .Site.Params.customCSS }}" />
  {{- end -}}
```

I got 2 options. 
1. remove "css" from `exampleSite/config.toml`
2. remove "css" from `layouts/partials/head.html`

I feel 2 is good but 1 is better for compatibility.
What do you think?

**Comment by dataCobra** [comment]
Hey @jlandowner, thank you for the detailed information. :+1: 

I like the first option way more than the second. This might be a bit restricted
if you want a specific path for the customcss but in my opinion the path default
is where the css files should stay.

**Comment by jlandowner** [comment]
Thank you for your reply and update.

And thank you for your good theme!
