### ISSUE TITLE
Embedded gist inherits styling from main CSS

### ISSUE THREAD

**Issue by muhannad0** [dataCobra/hugo-vitae#20]
Hi Ben.

Wanted to get your feedback on this. I tried to embed a gist using the short code. But the table styling in `main.css` is inherited to the gist styling somehow. Alternative rows are highlighted in gray. I've attached  screenshot to show how it looks.

I understand you might have including this styling for markdown tables.

I figured out the lines to fix the gist appearance are in `main.css`
- Line: 187 ; table th, table td, remove bottom-border
- Line: 202 ; table tbody tr:nth-of-type(even), remove background-color

What do you think of adding support to ignore any table styling if the div class=gist?
For example:
```
.gist table {
  all: unset;
}
```

Please excuse the suggestion if it's not correct. I'm not very familiar with CSS.

![hugo_vitae_gist_css_issue](https://user-images.githubusercontent.com/7235837/85236940-f2ee6000-b43b-11ea-96ef-c0d76673854a.png)

**Comment by dataCobra** [comment]
Hi Mohamed,

thank you for the information about the embeding of gists. I was not aware that my table styles would
make problems. I never used it before.

I'll look into this and give you a response at soon as I've a idea on how to approach this. :+1:

**Comment by muhannad0** [comment]
Thanks Ben.

I tried adding the following to `main.css`. It seems to fix the styling for the gist. Not sure if this is best practice for hugo themes, but it's a suggestion.

```
.gist table tbody tr:nth-of-type(even) {
  background-color: unset;
}

.gist table th, table td {
  border-bottom: unset;
}
```

**Comment by dataCobra** [comment]
Hey Mohamed,

could you send me your markdown file as a testing example for my changes?
This would help me a lot. :+1:

**Comment by muhannad0** [comment]
Sure thing. Here's the test post I was using. (rename the file extension to .md)
[test-gist.txt](https://github.com/dataCobra/hugo-vitae/files/4833658/test-gist.txt)

**Comment by dataCobra** [comment]
I've tried some different stuff and found your suggestion was the best to work around this problem.

@muhannad0, I would really appreciate if you could try this change out and give me feedback.
In a few days I will create a release with this fix.

**Comment by muhannad0** [comment]
Hi Ben. Just tested the with the new commit. The gist is displayed correctly, so its working fine. 👍
