### ISSUE TITLE
In-line code blocks are not very obvious

### ISSUE THREAD

**Issue by omajid** [dataCobra/hugo-vitae#24]
Hi, Thanks for creating this great theme!

I am really liking this theme and using it for my personal website. 

I noticed that - compared to many other themes - this one doesn't make in-line code fragments stand out. 

For example, in the following rendered text, it's hard to tell if the comma (",") in the second line is part of the code or not:

![image](https://user-images.githubusercontent.com/174451/87885258-9a7e9400-c9e2-11ea-9af3-7001f1b6f5b8.png)

I have seen several websites that adjust the foreground/background colours to make it more obvious when inline-code fragements start and end:

![image](https://user-images.githubusercontent.com/174451/87885361-4b852e80-c9e3-11ea-978a-690e00639393.png)

![image](https://user-images.githubusercontent.com/174451/87885366-55a72d00-c9e3-11ea-91e5-edd204a3ff44.png)

![image](https://user-images.githubusercontent.com/174451/87885372-60fa5880-c9e3-11ea-9137-add2220f2876.png)

Would it be possible to take such an approach for this theme? Thanks!

**Comment by dataCobra** [comment]
Hello @omajid ,

thank you for this information. The inline code should stand out more from the normal text.

I think this is a very important feature and I will prioritize this now over the others. :+1:

**Comment by dataCobra** [comment]
@omajid I've added some styling for inline code now. Please let me know what you think of it.

I will wait for your reply before I create a new release with this feature included.

**Comment by omajid** [comment]
Thanks for the quick fix. I have one piece of feedback: due to the colour choices, it's almost impossible to distinguish a code that is a link from a code that's not. Here's an example:

![image](https://user-images.githubusercontent.com/174451/87990451-054ad080-cab2-11ea-894b-4526ede70f45.png)

Here [`musl`](https://musl.libc.org) is supposed to be a link, but `glibc` isn't. Even github highlights them differently, but vitae doesn't :cry:

**Comment by dataCobra** [comment]
@omajid oh yeah not a great idea to make the color the same as the links. I'll fix that. :+1:

**Comment by dataCobra** [comment]
@omajid I've fixed the text color now and made the background a bit darker. Please again let me know what you think.

**Comment by omajid** [comment]
Thanks, that mostly solves all my concerns. I don't quite have an artist's eye, so I can't really say if making it darker is a good idea or not.

**Comment by dataCobra** [comment]
> Thanks, that mostly solves all my concerns. I don't quite have an artist's eye, 
> so I can't really say if making it darker is a good idea or not.

What is your personal opinion about the darker background?

Unfortunately I am not in a position to judge this for myself because I have not used it so often.
That is why your opinion about the background is so important to me. :+1:

**Comment by omajid** [comment]
> What is your personal opinion about the darker background?

I don't have a designer's sense of colours. I tried tweaking some colour values, and it seems like something just a little big lighter (`#F1F1F1`, compared to the current `#E1E1E1`) might be better? 

In my own quick tests, it looks like the lighter the background colour, the easier it is to tell whether the inline-code is a link or not. With `#F9F9F9`, for example, it's easier to tell link vs non-link in-line code snippets apart.

You can try this out on your end with this sample markdown that I used:

```
There are other C libraries on Linux too, such as
[`musl`](https://musl.libc.org/), but `glibc` is the most common one.
```

`#F9F9F9`:

![image](https://user-images.githubusercontent.com/174451/88247674-982f6a80-cc6c-11ea-9f74-56f14f8bf651.png)

`#F1F1F1`:

![image](https://user-images.githubusercontent.com/174451/88247781-fd835b80-cc6c-11ea-92df-d69d87624b1a.png)

`#E1E1E1`:

![image](https://user-images.githubusercontent.com/174451/88247716-bbf2b080-cc6c-11ea-8e8b-73c23591b91c.png)

(Or am I just seeing bad colours on my end?)

**Comment by dataCobra** [comment]
I will go with the color `#F1F1F1`, because with this background color it is neither too dark nor too light.

After I've changed that I will create a new release. :+1: 

Thank you for your help @omajid.

**Comment by dataCobra** [comment]
Thank you very much for your help on this issue @omajid. :+1:

I've made the changes as written in my last post and will now close this issue.

**Comment by omajid** [comment]
Thanks for fixing this so quickly!
