### ISSUE TITLE
Links of tags in pages are broken when hugo site is in a subdirectory

### ISSUE THREAD

**Issue by rogeriod** [dataCobra/hugo-vitae#26]
Not sure if this is a bug or a newbie issue (I'm new to Hugo).

I've decided to host the Hugo site files in a "/site" folder on my public web directory, as I have other assets on that folder.

I've updated the config.toml file and the Hugo site generates okay - all links take into consideration the "/site" bit on the url. However, the tags at the bottom of a post page will not update to include the "/site" bit - the url generated returns a 404 error page.

Is it a bug or am I missing something?
![Screen Shot 2020-07-31 at 19 55 41](https://user-images.githubusercontent.com/39655010/89069084-5ee0b400-d36a-11ea-84a7-721917e98460.png)

**Comment by dataCobra** [comment]
Hello @rogeriod, thank you for this report. :+1:

This seems to be a bug with the theme.

I'll look into this and give you some feedback.
If it really a bug I think it will be quite easy for me to fix.

Greetings Ben

**Comment by dataCobra** [comment]
Hello @rogeriod, this problem was a bug and not a newbie issue. :+1:

I've fixed it with the latest commit so you shouldn't get problems now if you
use the latest version from the master branch.

It is also very important to me to note that even if you "only" have an
understanding problem with the theme you are always welcome to open an issue.

**Comment by rogeriod** [comment]
Hi Ben,

That's brilliant. Many thanks!

Just one more question: does the theme allow for the link text colour on post titles and other links to be changed? I had a quick look at the CSS files but I couldn't figure it out.

Thanks again, best regards
Rogério

**Comment by rogeriod** [comment]
Thanks @dataCobra, appreciated.
