### ISSUE TITLE
href link in terms.html doesn't work

### ISSUE THREAD

**Issue by giovanialtelino** [dataCobra/hugo-vitae#29]
I was having an issue in the [terms.html](https://github.com/dataCobra/hugo-vitae/blob/master/layouts/_default/terms.html) file.

The Tag Cloud was generated but the absolute link (absURL) wasn't creating the last "/", so, for example, my links were 
"https://www.giovanialtelino.comtags/clojure/" instead of "https://www.giovanialtelino.com/tags/clojure/". And it only happened  after I generated the static files with **hugo**, while I was running on my machine with **hugo server** everything worked fine.

To solve it I just changed:

`<a href="{{ $.Site.LanguagePrefix | absURL }}{{ $data.Plural }}/{{ $value.Name | urlize }}/">{{ $value.Name }}<sup>{{ $value.Count }}</sup></a>`

to

`<a href="{{ $.Site.LanguagePrefix }}/{{ $data.Plural }}/{{ $value.Name | urlize }}/">{{ $value.Name }}<sup>{{ $value.Count }}</sup></a>`.

I'm not sure if this could be a breaking change since I don't know much of Hugo internals.

**Comment by dataCobra** [comment]
Hello @giovanialtelino,

thank you for this report. :+1:

I'm not able to reproduce your problem. For my test cases everything went as expected.

It would be nice if you could show me your `config.toml` file.

I hope we can find a solution for this.

Regards Ben

**Comment by giovanialtelino** [comment]
Yes for sure, if you want to I can also deploy an older version without the change I made.

```

baseURL = "https://www.giovanialtelino.com"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Giovani Altelino"
title = "Giovani Altelino"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright 2020, Giovani Altelino | Design [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "emacs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
    homepage = false
    
    keywords = ["hugo","clojure","c#","typescript", "sql"]

    description = "Software engineering blog and other (un)related themes."

    pagetitle = "Giovani Altelino"

    subtitle = "Software engineering blog and other (un)related themes."

    avatar = "/avatar.jpg"

    mainSections = ["post", "project"]

    highlightLanguages = ["go", "scala", "clojure", "c#", "angular", "react", "typescript", "YAML"]

	nofeedSections = ["about", "tags"]

    customCSS = "css/custom.css"

[params.comments]
enabled = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    url = "/about/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 5

    

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[params.social]]
    url = "https://github.com/giovanialtelino/"
    name = "Github"
    icon = "fab fa-github"
    weight = 1

[[params.social]]
    url = "https://twitter.com/GioAltelino/"
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2

[[params.social]]
    url = "https://www.linkedin.com/in/giovani-altelino/"
    name = "Linkedin"
    icon = "fab fa-linkedin"
    weight = 3

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    url = "/index.xml"
    weight = 4
```

**Comment by dataCobra** [comment]
Hey @giovanialtelino,

thanks again for this report. :+1:

With your help I was able to recreate and fix the problem. 

Thanks a lot. :slightly_smiling_face: 

Regards Ben

**Comment by giovanialtelino** [comment]
no problem, glad to help, I'm the one thankful for the nice theme!

Giovani..
