### ISSUE TITLE
head and header partials

### ISSUE THREAD

**Issue by nardoyala** [dataCobra/hugo-vitae#3]

**Comment by nardoyala** [comment]
Is there any reason why the head partial is the header and the header partial is the head?

I changed it in my forked version, but I'm curious about the reason for that.

**Comment by dataCobra** [comment]
Hey @nardoyala, this is probably a remnant from the theme that I used as a template for hugo-vitae. 

> I changed it in my forked version, but I'm curious about the reason for that.

Could you create a pull request with your fix for this mess?

**Comment by dataCobra** [comment]
I'm changing a few things on the theme right now. So I will make the change myself and commit. Then you don't need to make a pull request.
