### ISSUE TITLE
How do I change font?

### ISSUE THREAD

**Issue by wo0bo23go2** [dataCobra/hugo-vitae#30]
I want Sans-serif font from serif. Just put font into the webfont folder?

**Comment by dataCobra** [comment]
Hello @wo0bo23go2,

please add a description of your problem to this issue.

Otherwise I'm not able to help.

Regards Ben

**Comment by wo0bo23go2** [comment]
@dataCobra I edited.

**Comment by dataCobra** [comment]
Hello @wo0bo23go2,

it depends on what you want to do.

If you want to add your own font, create in your hugo web folder a new folder with the name static and in this a folder with name webfont.

Next you need to add these fonts into your custom CSS file.

Search for "how to add the fonts via CSS" in a searchengine and you will find a guide. You can also look into the main.css folder of the theme to see how it is done.

Regards Ben

**Comment by wo0bo23go2** [comment]
@dataCobra When I created and publish custom css file, My blog looks ugly. It looks like without hugo theme and css style.
