### ISSUE TITLE
Image thumbnail does not appear

### ISSUE THREAD

**Issue by ihzarizkyk** [dataCobra/hugo-vitae#31]
How do I display thumbnail images of each of my blog articles?

**Comment by dataCobra** [comment]
Hello @ihzarizkyk,

I'm very sorry but I don't understand what you mean with thumbnail image does not appear.

It would be nice if you could give me some morr information about your problem.

Regards Ben

**Comment by ihzarizkyk** [comment]
I mean, why when I display the Hugo blog article link, the thumbnail image does not appear like YouTube, which shows the thumbnail

**Comment by ihzarizkyk** [comment]
![Uploading Screenshot_2020-09-26-19-53-10-430.jpeg…]()
Like this post

**Comment by ihzarizkyk** [comment]
![Screenshot_2020-09-26-19-53-10-430](https://user-images.githubusercontent.com/56474969/94341331-b03bb580-0032-11eb-99fa-cb510eb2454d.jpeg)

Like this thumbnail youtube

**Comment by dataCobra** [comment]
I'm very sorry, but the feature you're looking for is currently not available for Hugo-Vitae.

Where did you read that this feature is available for Hugo-Vitae?

**Comment by ihzarizkyk** [comment]
Yes I know that, but you know image thumbnail?

**Comment by dataCobra** [comment]
I know what you mean, but I don't know how to implement this. If you want this feature in Hugo-Vitae add the feature and make a pull request please.

I have sadly no time to learn about implementation and also implementing it.

Regards Ben

**Comment by ihzarizkyk** [comment]
And then Why does it not appear when I make a markdown to display images on my posts? However, the header image can appear
