### ISSUE TITLE
Using Markdown Render Hooks to make links open in new tabs

### ISSUE THREAD

**Issue by nardoyala** [dataCobra/hugo-vitae#36]
I discovered today that you can make links rendered by Goldmark have the attribute `target="__blank"` in order to open in new tabs.

The only thing you need to do is to create a file called `render-link.html` inside a folder called `_markup` in your defaults as I show you here:

```
layouts
└── _default
    └── _markup
        └── render-link.html
```

That way you can change how Goldmark renders links. In order to make them open in new tabs the code must be something like this:

```html
<a href="{{ .Destination | safeURL }}"{{ with .Title}} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank"{{ end }}>
  {{ .Text }}
</a>
```

Do you think that's a good thing to add to your theme? I would be more than happy to make a pull request with that change if you believe that's something you'd like to have.

**Comment by dataCobra** [comment]
Hey @nardoyala,

thank you for this information. :+1:
I would really appreciate it if you could submit a pull-request for this feature.
I think it's a really good idea to make "_blank" the default link behavior.

Greetings, Ben

**Comment by nardoyala** [comment]
Excellent @dataCobra ,

I'm thrilled to contribute to your repo. I love your template and I built mine using yours as base.

I'll send you a pull request in an hour or so with this new feature.

Greetings.
