### ISSUE TITLE
Render images inside <figure> tags instead of <p> tags

### ISSUE THREAD

**Issue by nardoyala** [dataCobra/hugo-vitae#38]
Hi! It's me again,

I have a new propose for you. Hugo's markdown renderer puts images inside `p` tags. I found that behavior awful, so I've change that in my theme with a render hook.

Do you believe that's something you'd want for your theme? If that's the case I'll be more than happy to create a PR adding that small modification.

I will create a new file called `render-image.html` inside the _markup folder:

```bash
layouts
└── _default
    └── _markup
        ├── render-image.html
        └── render-link.html
```

The file will have this content:

```html
<figure>
  <img src="{{ .Destination | safeURL }}" alt="{{ .Text }}" {{ with .Title}} title="{{ . }}"{{ end }} />
</figure>
```

Let me know if that will be something you'll want, I'll be more than happy to make that small change.

**Comment by dataCobra** [comment]
Hey @nardoyala,

Thanks for your contribution, I like the idea of changing the tags for images from `<p>` to `<figure>`.
It would be really nice if you could create a PR for this small change.

I'll check the behavior with this change afterwards so you don't need to.

Regards, Ben

**Comment by nardoyala** [comment]
Excellent! Thank you for letting me contribute. I'll send you a pull request at some point of this day.

Regards, Bernardo.
