### ISSUE TITLE
emojis and bold text are not displaying

### ISSUE THREAD

**Issue by henryhe1** [dataCobra/hugo-vitae#4]
not recognizing [emojis](https://themes.gohugo.io//theme/hugo-vitae/post/emoji-support/) or **bold text** from markdown. Is this something I have to make a custom CSS for? 

_italics_ currently work

**Comment by henryhe1** [comment]
Seems like any html in markdown is not being generated. Including embeds, emojis, etc

**Comment by dataCobra** [comment]
Hello @henryhe1,

it would be easier for me if you show me snippets of what exactly you try.

**Comment by henryhe1** [comment]
Hey @dataCobra , thanks for the reply! This is very helpful. I was mainly intending to use html for centering text as well as embedding soundcloud links. 

And emojis do work for me now with enableEmoji set to true and using shorthands; before I was trying to copy the exampleSite emoji post which didn't work. 

Regarding the bold text, I believe it is working when I zoom in, I think the bold font weight just looks similar to the normal font weight. How can I increase the weight of the bold font? Cheers, and great work on the theme! :)

![image](https://user-images.githubusercontent.com/12023120/78684649-b8eed280-78be-11ea-8381-6d3619188e1a.png)

**Comment by dataCobra** [comment]
@henryhe1 that is a strange behavior. But if you want to try a higher font-weight, you could add the following to your custom CSS.
```
b, strong {
  font-weight: 700;
}
```
Could you tell me which browser you're using to display the page?

Since I am currently working on the redesign, I can use this information to directly correct such errors for the future.

Thank you for reporting this errors :+1:

**Comment by henryhe1** [comment]
@dataCobra thanks a lot. It is working but just doesn't pop out on screen enough even with the weight at 700. I like Roboto but I just switched to OpenSans to make it easier. I am using Chrome. Looking forward to the redesign!

![image](https://user-images.githubusercontent.com/12023120/78903329-f7b09400-7a48-11ea-929b-86cdcc9e71b6.png)

**Comment by dataCobra** [comment]
@henryhe1 thanks for your answer. :slightly_smiling_face: 

I will close this issue now. :+1:
