### ISSUE TITLE
Feature Request: Social Media Share buttons are highly desirable for Posts.

### ISSUE THREAD

**Issue by kesseract** [dataCobra/hugo-vitae#41]
It will be great if share buttons LinkedIn, Twitter, Facebook, etc can be added to all Posts in this fantastic theme.

**Comment by dataCobra** [comment]
Hey @kesseract,

because the theme should be GDPR user-friendly, this is pretty hard to implement.

I would need to add a fully functional cookie consent with all the necessary stuff for GDRP law.

For the time being this is would take up to much of my time.

Regards, Ben
