### ISSUE TITLE
Definition of the target URL in the title

### ISSUE THREAD

**Issue by fourstepper** [dataCobra/hugo-vitae#42]
Hi,

First of all, thanks for the great theme!

I have come across an issue when deploying the website that wasn't apparent when testing the site on localhost, which is the behaviour of the title. When I click the title (Robin Opletal on this page: https://robinopletal.com/) I get redirected to localhost:1313 instead of getting redirected to the baseURL of the website (which would've been expected)

I have changed nothing to the source files of the theme.

Thanks for any pointers to where the issue could be.

**Comment by dataCobra** [comment]
Hi @fourstepper,

this seems to be a problem with your configuration file for your Hugo website.
Please check your configuration file for the "baseURL" it seems like you forgot to change this to "https://robinopletal.com".

I hope this helps and can fix your issue.

Greetings, Ben

**Comment by fourstepper** [comment]
Hi Ben,

Thank you for the reply.

I believe this is not the case. As deployed at https://robinopletal.com, the code is available at https://gitlab.com/opletalrobin/robinopletal.com, with all the hugo site data being under the site/ folder - baseURL is set correctly.

I might have found the issue though..

Layer 12: https://hub.docker.com/layers/fourstepper/robinopletal.com/latest/images/sha256-bb09523da6239bc4c5000e12f9f3b6af7b70a0e9c89cd988edf9c6a50c4ab39e?context=repo specifies the hugo base URL in the ENV... This could very well be the problem.

Let me try changing that and I will get back to you if I still encounter any issues :)

**Comment by fourstepper** [comment]
Alright, solved it like this in the relevant Dockerfile:

https://gitlab.com/opletalrobin/robinopletal.com/-/blob/master/Dockerfile

1) Had to set the correct HUGO_BASE_URL in the Dockerfile
2) Had to set --appendPort to false

Thanks for the help @dataCobra

**Comment by dataCobra** [comment]
Thanks for the reply @fourstepper. :+1:

I've never used docker for Hugo website deploy. Good to know that for the future. :slightly_smiling_face:

Thank you.

- Ben

**Comment by fourstepper** [comment]
Actually, I am still having some issues now, possibly because now the container behind traefik is only listening to https://robinopletal.com

**Comment by fourstepper** [comment]
Well okay, as I managed to solve that too, here is the full dockerfile - the hugo website just has to be in the site/ subdirectory compared to the Dockerfile

https://gitlab.com/opletalrobin/robinopletal.com/-/blob/master/Dockerfile

I was missing --bind=0.0.0.0
