### ISSUE TITLE
Theme is missing .woff2 font-files for FontAwesome (solved) -> Still open as a reminder

### ISSUE THREAD

**Issue by ndy40** [dataCobra/hugo-vitae#43]
The theme makes a request for `fa-brands-400.woff2` but that isn't present.

**Comment by dataCobra** [comment]
What exactly was your problem?

**Comment by ndy40** [comment]
Creating a PR shortly.

**Comment by dataCobra** [comment]
I've solved the problem with commit b7e5602.

@ndy40, for future testing I would really like to know which smartphone and browser you used to stumble across this problem.

**Comment by ndy40** [comment]
@dataCobra  

Sure would do. I intended to provide that info but the person wasn't responsive. Thanks for the update all the same.

**Comment by dataCobra** [comment]
I'll let this issue open for now as a reminder for me.

Because I still want to try to use only the woff file-format for FontAwesome in the future. Also to reduce the theme size.

**Comment by ndy40** [comment]
Got that info from the person. 

Phone Model - Samsung A10 
Browser - Chrome

**Comment by dataCobra** [comment]
Thanks a lot for this information.

Could you ask the person also for the android version in use?

This would help me a lot. :+1:

**Comment by ndy40** [comment]
So the Android version is 10. 

The issue with the site has nothing to do with the work you have done. There were some CORS errors as a result of how the person connected to the internet. He later tried it on a different mobile network and the theme works without issues. 

Sorry for the false alarm.

**Comment by dataCobra** [comment]
Thank you for the information anyways @ndy40. :+1:

Since I've removed all unnecessary webfont types I can close this issue now.
