### ISSUE TITLE
Possibility to align images

### ISSUE THREAD

**Issue by GaetanLepage** [dataCobra/hugo-vitae#46]
I know that some of the Hugo themes (such as Icarus and Hermit) offer a way to align images (included thanks to the `figure` shortcode) to be aligned left or right.

I basically know nothing about css but understood that they used the `class` attribute to invoke a css style:
```{{< figure src="/img/my_image.png" width=200 class=alignleft >}}```

```
.left,
.alignleft {
  float: left;
}
.right,
.alignright {
  float: right;
}
```

I tried to manually edit the `/static/css/main.css` file of the vitae theme but did not succeed to get any result.
Could that be possible to achieve ?

**Comment by dataCobra** [comment]
Hey @GaetanLepage, 

I've heard about this method. I'll will check how it can implemented the best and try to add it to the theme. :+1:

Greetings, Ben

**Comment by dataCobra** [comment]
Hey @GaetanLepage,

currently I'm working out how to proceed with the theme and what improvements and changes to consider for an upcoming release.

I've added this as part of the milestone to version 3.0.

So it is very likely that this feature will find its way into the theme with the next major release. :+1:

**Comment by dataCobra** [comment]
Hey @GaetanLepage,

The next version of Vitae is coming soon and I have managed to include this feature in the new version.

**Comment by GaetanLepage** [comment]
Thank you very much !!!
