### ISSUE TITLE
KaTeX inline equations not rendering

### ISSUE THREAD

**Issue by GaetanLepage** [dataCobra/hugo-vitae#48]
Hello !
I am trying to embed maths in my website.
The block equations ($$x = 1$$) are rendering as expected. However, inline ones are not working (foo $x=1$ bar).

I don't know if this issue comes from KaTeX or not.
Is there a way to use Mathjax instead of KaTeX as it would maybe solve the issue ?

**Comment by dataCobra** [comment]
Hey @GaetanLepage,

since Hugo 0.62 inline math was no longer working.

I've added a workaround so your inline math code should work now.

Use the latest version of the master branch and test it for you please.

**Please give me a feedback if it worked or not.**

**Comment by GaetanLepage** [comment]
Dear @dataCobra,
I confirm you that it works thanks to the latest version !

Thank you for the quick fix :)
