### ISSUE TITLE
Deploy on Netlify?

### ISSUE THREAD

**Issue by wondercomm** [dataCobra/hugo-vitae#49]
Hi, 

I am a newbie to static websites, I was wondering if there is any documentation available on how to deploy this theme on netlify? So far, I was able to fork the theme, and then when I go to Netlify to deploy from my gihub, I need to enter the following: 
1. Build Command 
2. Publish Directory 

Any help that you can provide on this would be greatly appreciated. 
Thanks !

**Comment by dataCobra** [comment]
I'm sorry but I have no knowledge in netlify.

Maybe there is information about it in the Hugo wiki?

Greetings

**Comment by wondercomm** [comment]
No worries, I'll try to figure it out. Netlify is a hosting platform like godaddy. Netlify works seamlessly with many hugo easy set up themes. It looks for a netlify.toml file in the root directory where the build command and location of public directory are stored. Once I figure it out, I'll update this thread. Thank you for replying.

Sincerely,
Varun Singh

________________________________

**Comment by sophiabrandt** [comment]
@wondercomm Did you see the docs on how to deploy to Netlify on the [official homepage for Hugo](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/)?

As to your question, the settings should be (if you didn't change anything):

Build command:  `hugo --gc --minify`
Publish directory: `public`

**Comment by wondercomm** [comment]
Thanks, I;ll certainly give it a try. What netlify looks for in the .toml file is the build command, publish directory and the version number for hugo environment.

**Comment by dataCobra** [comment]
Hey @wondercomm,

what is the status for this issue?

**Comment by wondercomm** [comment]
I couldn't find time to dig deeper into web hosting as it's not my expertise. So for now, I've shelved this project until I find some more clarity.

In simple words and from my understanding, netlify (the hosting platform) is looking for a netlify.toml file in the main folder which should contain the Hugo version and site name, I suppose.

Look at Meghna-hugo theme on Hugo themes, they have an easy deployment on netlify. That is what I'm looking for replicate.

Thanks for reaching out.

- Varun

________________________________

**Comment by dataCobra** [comment]
Thank you for answering this quick! :+1:

Maybe someone else who is comfortable with netlify deployment will pickup this issue in the future.

For now I'll see this as backlog.

- Ben

**Comment by wondercomm** [comment]
Sure. Keep me posted if anything happens.

Cheers!

- Varun

________________________________

**Comment by dataCobra** [comment]
It's over a year without any update on this topic.

I'll close this issue for now.

Maybe this link will help you:
 -> https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

Regards,
Ben
