### ISSUE TITLE
Absence of favicon

### ISSUE THREAD

**Issue by gabrielcaussi** [dataCobra/hugo-vitae#52]
I couldn't find the option to set up favicon. Could you let me know how to proceed?

**Comment by dataCobra** [comment]
Hello @gabrielcaussi,

Yeah sadly I don't have a proper documentation for all features yet.

Here is what you need to do:

 1. Activate favicons in your site configuration: [Link to the example](https://github.com/dataCobra/hugo-vitae/blob/master/exampleSite/config.toml)
 2. Make sure you have the favicon in 16x16 and 32x32 pixels
 3. Copy the favicon to the `static/` folder with the names `favicon-32x32.png` and `favicon-16x16.png`
 4. Clear the browsercache for you website and check if the favicon works. (Sometimes this takes a while)

After testing please answer here if it worked or not.

**Comment by gabrielcaussi** [comment]
Thanks @dataCobra,

Using this guide you went through I managed to make it work. Very beautiful theme!
