### ISSUE TITLE
Bug: Instagram shortcode in Example Site breaks the site

### ISSUE THREAD

**Issue by nardoyala** [dataCobra/hugo-vitae#53]
There's a bug with the Example site that comes from Facebook blocking access to the public Instagram's API (You can read more about this [here](https://github.com/gohugoio/hugo/issues/7879)).

That causes that, when running `hugo serve` with the example site, the terminal returns this error message:

```shell
ERROR 2021/05/08 09:40:05 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Bad Request
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
```

There's no simple solution for that, you must set up a Facebook developer account and configure your access to the API.

So, the solution I propose for the theme is simple to delete the shortcode inside `rich-content.md`.

If you think that would be a good fix for this, please let me know and I'll send a PR with that change.

**Comment by dataCobra** [comment]
Hey @nardoyala,

removing the page from the exampleSite is the easiest and best solution for this.

I would really appreciate if you create a PR for this.

Regards,
Ben

**Comment by nardoyala** [comment]
Excellent!

I'll send you the PR right away and I'll connect it with this Issue.

Best regards,
Bernardo.
