### ISSUE TITLE
Symbols don't render correctly in links

### ISSUE THREAD

**Issue by sophiabrandt** [dataCobra/hugo-vitae#55]
Thanks for creating this theme.

In my blog I have several links where the link text contains an ampersand.

Example:

[Dungeons & Dragons](https://dnd.wizards.com/)

The theme renders them like so (it shows `&amp;` instead of `&`):

[Dungeons \&amp; Dragons](https://dnd.wizards.com/)

Is there a way to opt out of HTML escaping for links? 
Just putting a `\` before the `&` does not seem to work.

I know that Hugo has a function called [HtmlUnescape](https://gohugo.io/functions/htmlunescape/), but as I'm using plain markdown, I am unsure on how to incorporate that function.

This post is the most relevant on the Hugo forums that I could find, but it seems to address a different issue:
https://discourse.gohugo.io/t/ampersand-character-in-markdown-links/25269

Any tips are appreciated.

**Comment by dataCobra** [comment]
Hello @sophiabrandt,

Thank you for reporting this problem.

I'll look into this and answer you when I solved it.

Regards,
Ben

**Comment by dataCobra** [comment]
I've found a solution to this problem and created a fix for that.

If you use the repository to build your website you only need to pull the changes.

I'll now create a release file. Might take a few minutes before it shows up in the releases.

**Comment by sophiabrandt** [comment]
@dataCobra works splendidly, thank you very much! :+1:
