### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by GaetanLepage** [dataCobra/hugo-vitae#56]
Hello !

Is it planned to add support for a dark theme ?
I don't think it is absolutely necessary but it might look pretty nice on Vitae !

**Comment by dataCobra** [comment]
Hi @GaetanLepage,

I am currently working on a dark mode for the theme, this mode can already be found in the develop branch.

If you want to have a look at it I have the current develop branch running on my website. https://thinkbot.de/en/

**Comment by GaetanLepage** [comment]
Oh great !
It looks very nice :)

**Comment by dataCobra** [comment]
@GaetanLepage I'll close this issue because version 3.0 is on the way and dark mode is already implemented. :+1:
