### ISSUE TITLE
Lightbox implementation

### ISSUE THREAD

**Issue by davidkaufmann** [dataCobra/hugo-vitae#57]
I would love a lightbox implementation for version 3.
I like [spotlight.js](https://github.com/nextapps-de/spotlight) and already have a prototype running using custom shortcodes.
I can submit a PR in case this is something you're interested in.

**Comment by dataCobra** [comment]
Hey @davidkaufmann,

this looks interesting, but the implementation would not match my idea of keeping the base of the theme as small and simple as possible.

Also this would be another implementation I would need to maintain.

If you want to add this to your version of the theme, would the customjs header partial that you mentioned in #58 help you

Regards,
Ben

**Comment by davidkaufmann** [comment]
Hi @dataCobra,

issue #58 will do the job and come in handy later when implementing other stuff 👍🏻
Issue resolved, hence closed 😄
