### ISSUE TITLE
Add customjs to header partial

### ISSUE THREAD

**Issue by davidkaufmann** [dataCobra/hugo-vitae#58]
There is a customcss option, a customjs is missing.
Adding functionality such as [Lightboxes ](https://github.com/dataCobra/hugo-vitae/issues/57) becomes harder and sometimes impossible without touching the Theme itself.

**Comment by dataCobra** [comment]
Hey @davidkaufmann 

As described in the other issue #57, this here is the variant I find best to make it easier for others to use JS in the future.

Because I don't have much time at the moment, I would be happy if you would create a PR for this.

Regards,
Ben

**Comment by davidkaufmann** [comment]
Hi @dataCobra,

I implemented this in #59.
Happy to see this merged 😃

Take care!
