### ISSUE TITLE
Disqus showing console error

### ISSUE THREAD

**Issue by viniciusalmada** [dataCobra/hugo-vitae#6]
Disqus is not loading and showing an:
`Uncaught TypeError: Cannot read property ‘appendChild’ of null`.

**Comment by viniciusalmada** [comment]
To fix it, you may had to add the following piece of code to the top of `layouts/partials/disqus.html`:
```html
<!--Fix: Uncaught TypeError: Cannot read property ‘appendChild’ of null-->
<div id="disqus_thread"></div>
```

**Comment by dataCobra** [comment]
Thanks you for this issue. :+1: 
I've added the `<div>` tag so this should work now.
