### ISSUE TITLE
Enhancing post title with reading time, word count and author name

### ISSUE THREAD

**Issue by sarathmekala** [dataCobra/hugo-vitae#60]
Hi Benedikt,

I have enhanced the post metadata to include reading time, word count and author name as shown below. These fields are configurable and can be toggled on/off.

[![contrib.png](https://i.postimg.cc/xdQBgvCT/contrib.png)](https://postimg.cc/HrSSk7Xf)

If you are ok with this idea I will raise a pull request

**Comment by dataCobra** [comment]
Hi @sarathmekala,

that looks amazing! It would be nice if you would create a PR.
Does your version also include the possibility to add a href to the Author?

Here is how I implement it at the moment:
```
	<div class="author">
	{{ if eq .Site.Params.listAuthor true}}
	{{ if isset .Params "author" }}
		<p>
		{{ if isset .Params "authorlink" }}
		{{ i18n "authorpretext" }} <a href="{{ relURL .Params.authorlink }}" target="_blank" rel="noopener noreferrer">{{ .Params.author }}</a>
		{{ else }}
		{{ i18n "authorpretext" }} {{ .Params.author }}
		{{ end }}
		</p>
	{{ end }}
	{{ end }}
	</div>
```

**Comment by sarathmekala** [comment]
@Benedikt Great 🙂. I can update the code to make the author as a hyperlink.. will change and raise a PR

**Comment by dataCobra** [comment]
@sarathmekala thank you! :+1:

Currently the author name is only a hyperlink when the param `authorlink` is given as an option in the front matter of a content file. When this param is not available the author name will be displayed as normal text. This gives people who use the theme the option to choose if there want the author name to be a hyperlink or not.

Please don't forget to read the [information about contributing](https://github.com/dataCobra/hugo-vitae/blob/master/CONTRIBUTING.md) to the project.

**Comment by sarathmekala** [comment]
I have raised a pull request @ https://github.com/dataCobra/hugo-vitae/pull/61. Please review.

**Comment by sarathmekala** [comment]
@dataCobra Please get back to me if you need any further info from me.

**Comment by dataCobra** [comment]
Thanks for the offer. If I need further information I'll get back to you. :)

**Comment by dataCobra** [comment]
Hey @sarathmekala,

FYI: There were a few bugs in your code. I took care of the problems and corrected them myself.

If you want to know what the problem was, here is the commit: 76ac64b6c800c796eff7ec8b28049eb9a8ea2791

**Comment by sarathmekala** [comment]
@dataCobra ok. LGTM. Thanks.

Closing this issue as the code has got merged.
