### ISSUE TITLE
How enable the dark-theme

### ISSUE THREAD

**Issue by leandrolmb** [dataCobra/hugo-vitae#66]
Hello,

how do i turn on dark mode (showing and clicking the moon icon)? Also and make the default dark-mode page?

Tks

**Comment by dataCobra** [comment]
Hi @leandrolmb,

dark-mode is activated by pressing the moon icon and deactivated when pressing the sun icon. The dark-mode stays activated when you pressed the moon-icon.

There is currently no option to set one as default for the people that are coming to view your site.

**Comment by dataCobra** [comment]
Thanks for pointing out that there is no default dark-mode.

I've committed some changes so it is possible to make the darkmode the default.

If you want to know how, use the latest version of Vitae and check the `config.toml` in the `examples/` folder.

**Comment by leandrolmb** [comment]
Oh ok, I would comment that I wasn't finding it. I will test it, thanks.

**Comment by dataCobra** [comment]
Please give me feedback if it worked for you. So I can close the issue. :+1:

**Comment by leandrolmb** [comment]
Working!

Just a little detail at `config.toml` example file:

change the `seURL = "http://example.org/"` to `'ba'seURL = "http://example.org/" first line`.

cause this little problem:

![http](https://user-images.githubusercontent.com/58884687/127015904-f030e63d-2b03-4766-9a08-0ebc2044bc57.png)

Thanks!!

**Comment by dataCobra** [comment]
@leandrolmb yeah I found this issue while changing the config.toml and fixed it already.

But I forgot to add it to the release... Thanks for pointing this out. :+1:

I'll close this issue now.
