### ISSUE TITLE
Desactivate comments disqus for specific page

### ISSUE THREAD

**Issue by leandrolmb** [dataCobra/hugo-vitae#67]
Hello @dataCobra 

Maybe i'm doing something wrong, but IDK... The comments are not disabling for specific pages. My page is in `/content/contato.md` and `/content/homepage.md`

The parameters in `config.toml`:

`# Comments`
`[params.comments]`

`# Enable Comments with "true"`
`enabled = true`

`# Comment provider:`
`engine = "disqus"`

`# Desactivate comments for specific page types`
`disableOnTypes = ["contato","homepage"]`

`[params.comments.disqus]`
`shortname = "lmbtic"`

**Comment by dataCobra** [comment]
Hey @leandrolmb,

for single content pages you need to use the front matter on the page. It's called `commentable`. It can be either true or false.

The `disableOnTypes` feature is only for nested content in directory. For example `/content/post/article.md`, then you need to set `disableOnTypes = ["post"]` then all content below the post directory is not commentable.

I hope this helps you.

Regards,
Ben

**Comment by leandrolmb** [comment]
Thanks for the clarification @dataCobra now it's working! ;)
