### ISSUE TITLE
Internal templates are not available

### ISSUE THREAD

**Issue by sophiabrandt** [dataCobra/hugo-vitae#70]
I was thinking about implementing [Twitter Card metatags](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards) and `og:image` (OpenGraph) metatags for better sharability on social media.

In `layouts/partials/head.html` there are references to several internal templates:
```
{{ template "_internal/opengraph.html" . -}}
{{ template "_internal/twitter_cards.html" . }}
{{ template "_internal/schema.html" . }}
```
This implies that the metatags should be implemented in those templates.

However, I cannot find them in the theme. Are they not available to the public?

In any case, thank you for the work on the theme.

**Comment by dataCobra** [comment]
Hello @sophiabrandt,

the templates that you mentioned are available trough **Hugo**  and they will be generated when creating the website with `hugo command. The only thing I need to do as a theme creator is to load them in via`{{ template "..." . }}`.

If you want to know more about how to use these templates take a look at the Hugo documentation.
 - https://gohugo.io/templates/internal/

I hope this will help. :+1:

If you've more questing regarding this topic, feel free to ask.

Regards,
Ben

**Comment by dataCobra** [comment]
Just one more info regarding the `images = ['...']` front matter for the content.

If you want to use images make sure the first one in the list is the one that should also be displayed on the post page.

**Comment by sophiabrandt** [comment]
Huh. :laughing: Thanks for clearing that up.
It did not occur to me to check the Hugo documentation, sorry. :sweat_smile:

**Comment by dataCobra** [comment]
No worries. :+1: :slightly_smiling_face:
