### ISSUE TITLE
Code in hyperlink doesn't render

### ISSUE THREAD

**Issue by omajid** [dataCobra/hugo-vitae#74]
```markdown
- Github: [`@omajid`](https://github.com/omajid)
```

Gets rendered as:

![image](https://user-images.githubusercontent.com/174451/129133566-e179a559-7d30-4de2-aea9-d9e83fcb53a9.png)

And 

```markdown
- Github: `[@omajid](https://github.com/omajid)`
```

Gets rendered as 

![image](https://user-images.githubusercontent.com/174451/129133636-fe6856db-7c25-49eb-b05c-8a06f93f3151.png)

This didn't happen in a previous release of vitae.

[PaperMod](https://github.com/adityatelange/hugo-PaperMod) renders this as I expect:

```markdown
- Github: [`@omajid`](https://github.com/omajid)
````

![image](https://user-images.githubusercontent.com/174451/129133745-26c669e8-3ed6-4c78-a6e9-d800d2e2eecc.png)

A git bisect suggests it was introduced by commit 478e476b3f211572b5a82bffabce79dc18867fbf. Deleting `layouts/_default/_markup/render-link.html` does indeed fix the issue.

**Comment by dataCobra** [comment]
Hi @omajid,

thanks for informing me about the bug.  :+1:
Because of your hints it was easy for me to reproduce the bug and fix it.

I'm in the process of creating a new release. So you can download a new version shortly without the problem.

Regards,
Ben

**Comment by omajid** [comment]
Thanks for the quick fix!
