### ISSUE TITLE
use safeURL

### ISSUE THREAD

**Issue by 0xYUANTI** [dataCobra/hugo-vitae#76]
is there any reason not to use safeUrl in layouts/partials/header.html as documented here:

https://gohugo.io/functions/safeurl/

the change would be adding "| safeUrl' in a few places (e.g. line 48) and the benefit would be that it would let us use irc:// links and such (anything other than http/s and mailto)

**Comment by dataCobra** [comment]
Hi @0xYUANTI,

I'll have a look at it. Thanks for bringing it to my attention. :slightly_smiling_face: 

Regards,
Ben

**Comment by dataCobra** [comment]
I'm currently pretty busy, but I'll try to work on this in the next couple of days.

Regards Ben
