### ISSUE TITLE
Dark mode icon is not shown if no social links are specified

### ISSUE THREAD

**Issue by leozqi** [dataCobra/hugo-vitae#78]
Hello and thanks for the great theme,

If no social links are specified through `params.social` while using this theme, the dark mode icon is not rendered on the blog's header. Changing the [`layouts/partial/header.html`](https://github.com/dataCobra/hugo-vitae/blob/main/layouts/partials/header.html) file fixes this issue. 

I've tested a solution that works for me and will submit it as a pull request.

**Comment by dataCobra** [comment]
Hello @leozqi,

thanks you for the information and the fix. :+1: 

I'll review the PR and merge is ASAP.

Thanks,
Ben
