### ISSUE TITLE
Term with hashtag causing 404 error

### ISSUE THREAD

**Issue by ozzie-eu** [dataCobra/hugo-vitae#81]
I was testing the tags on my [personal site](https://www.ozzie.eu/) and one with the '#' character caused a 404 - Not Found error.
The source file from the Hugo theme rendering the tag links is (\hugo-vitae\layouts\_default\terms.html).
I was able to solve it locally, for the '#', replacing it with a the '#23' sequence:
> <a style="font-size: {{ $curFontSize }}rem;" href="{{ absURL $data.Plural }}/{{**replace $value.Name "#" "%23"** }}/">

The theme should replace special characters with [URL encoding](https://www.w3schools.com/tags/ref_urlencode.ASP) sequence on the tag links.

**Comment by dataCobra** [comment]
Hey @ozzie-eu, thanks for creating in Issue. Currently im very busy, but I'll try to take a look in the next couple of days.

Regards Ben

**Comment by dataCobra** [comment]
I finally got the time to take a look at the problem.

Sadly there is no way to fix this issue with Hugo functions at the moment, but your change does fix this problem for now.

I added your change to the develop branch and test it some more in the next days. When I'm sure it does not break
something else, I'll add it to the main branch.

Thank you for helping to make the theme better!
