### ISSUE TITLE
Support for Persian?

### ISSUE THREAD

**Issue by farooqkz** [dataCobra/hugo-vitae#86]
Hello there. Very nice template, been using it in [my website](https://far.chickenkiller.com). But I am about to launch a Persian blog as well. Does it support RTL langugages like Persian? If yes, how can I use it? If no, How can I contribute translations or support for Persian?

ping @dataCobra

**Comment by dataCobra** [comment]
Hello @farooqkz,

since the rendering of the website is done by hugo and not the theme. I recommend you to check
the documentation of hugo. I've sadly no idea if RTS languages work.

Regards,
Ben

**Comment by dataCobra** [comment]
Hey,

this sounds very nice.

Let me know when you're finished.

Regards,
Ben

**Comment by dataCobra** [comment]
Hello @farooqkz,

how far is your persian translation of the theme?
Are you still working on it or can I close this issue?

**Comment by farooqkz** [comment]
No I am not working on this anymore as I don't want to launch my Persian blog anymore.
