### ISSUE TITLE
When blog is in a subdirectory, resources does not load

### ISSUE THREAD

**Issue by s1lviu** [dataCobra/hugo-vitae#90]
Hi,

When `BaseURL = 'https://domain.com/blog/'`, the resources do not load; the base URL is not set to `/blog/` in the generated index.html and posts/pages.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/9863576/206867783-3c944fb1-6e4b-4d39-956d-d5e2838c37bb.png">

When `BaseURL = 'https://domain.com/'`, it is all ok.

`hugo v0.108.0+extended darwin/arm64 BuildDate=unknown`
Latest hugo-vitae theme

Thanks!

**Comment by dataCobra** [comment]
Hello @s1lviu,

thank you for inform me about this issue. I can reproduce it.

I'll fix it and let you know when the fix is available.

Regards,
Ben

**Comment by dataCobra** [comment]
@s1lviu I've found the issue and fixed it.

Please test the theme now with the new commit and let me know if the issue is gone.

Regards,
Ben

**Comment by dataCobra** [comment]
If you used the example config as your base, please make sure to remove trailing slashes from
all relative URLs.

**Comment by s1lviu** [comment]
It is working perfectly now - thanks @dataCobra! Have a great weekend!

**Comment by s1lviu** [comment]
It is working perfectly now - thanks @dataCobra! Have a great weekend!

**Comment by dataCobra** [comment]
Glad I could help. :slightly_smiling_face: 

I wish you a great weekend too!
