### ISSUE TITLE
missing google_analytics_async.html partial.

### ISSUE THREAD

**Issue by swilcox** [dataCobra/hugo-vitae#97]
The current version seems to not work out of the box due to a missing partial... `_internal/google_analytics_async.html`.

Creating an empty file in ` ./layouts/_internal/` resolves the error, but obviously could mean issues for someone who needed google analytics.

**Comment by dataCobra** [comment]
It seems the latest PR fixed the issue.

Are you able to confirm this?

**Comment by swilcox** [comment]
Yes, that does fix it. Thank you!
